icinga2_rest_api:
  icinga2_url: 'https://localhost'
  icinga2_api_port: '5665'
  username: 'root'
  password: 'fd98a19801b15c57'
icinga2_rest_endpoints:
  package_endpoint: '/v1/config/packages/'
  stage_endpoint: '/v1/config/stages/'