version: '3'
services:
  flask_rest_facade:
    build: .
    ports:
      - "6000:5000"
    volumes:
      - ~/auto_monitoring_cmdb/configs.yaml:/opt/configs.yaml
      - ~/auto_monitoring_cmdb/app.py:/opt/app.py
  icinga2:
    image: "jordan/icinga2:latest"
    ports:
      - "80:80"
      - "5665:5665"

